Page_Controller:
  extensions:
    - S3PageExtension
Image:
  extensions:
    - S3ImageExtension
MigrateThemeToS3:
  skipFoldersDuringImport: [lang,templates]
Injector:
  RequestProcessor:
    properties:
      filters:
        - '%$ImageURLRequestFilter'
  S3Facade:
    properties:
      migrationFolders: ['assets']
  ImageURLRequestFilter:
    properties:
      foldersForRewrite: ['assets/','themes/sep2015/']
      foldersToSkipDuringRewrite: ['assets/Uploads/_resampled','assets/_resampled']
  S3ImageExtension:
    properties:
      s3Facade: %$S3Facade
  S3ImageExtension:
    properties:
      s3Facade: %$S3Facade
